[package]
name = "TaskTracker"
version = "0.1.0"
edition = "2024"

[dependencies]
prettytable-rs = "0.10.0"
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.97"